kind: pipeline
name: default

steps:
- name: backend
  image: node:11
  environment:
    NODE_ENV:
      from_secret: NODE_ENV

    HOST:
      from_secret: HOST
    PORT:
      from_secret: PORT

    CLIENT_ID:
      from_secret: CLIENT_ID
    CLIENT_SECRET:
      from_secret: CLIENT_SECRET
    REDIRECT_URL:
      from_secret:

    SPREADSHEET_NAME:
      from_secret: SPREADSHEET_NAME

    DB_HOST: database
    DB_NAME:
      from_secret: DB_NAME
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    POSTGRES_PASSWORD:
      from_secret: POSTGRES_PASSWORD

    SESSION_COOKIE_NAME:
      from_secret: SESSION_COOKIE_NAME
    SESSION_HEADER_NAME:
      from_secret: SESSION_HEADER_NAME

    CRYPTO_ALGORITHM:
      from_secret: CRYPTO_ALGORITHM
    CRYPTO_PASSWORD:
      from_secret: CRYPTO_PASSWORD
    CRYPTO_SALT:
      from_secret: CRYPTO_SALT
    CRYPTO_KEYLENGTH:
      from_secret: CRYPTO_KEYLENGTH
  commands:
  - sleep 15
  - yarn install
  - yarn run build
  - node ./app/build/index.js
  when:
    branch:
      - drone
    event:
      - push

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    POSTGRES_DB:
      from_secret: DB_NAME
