// flow-typed signature: 633b8bb7963d7e2d0d9cc5bef6307135
// flow-typed version: <<STUB>>/eslint_d_v^7.3.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint_d'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint_d' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint_d/bin/eslint_d' {
  declare module.exports: any;
}

declare module 'eslint_d/bin/eslint' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/linter' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint_d/bin/eslint_d.js' {
  declare module.exports: $Exports<'eslint_d/bin/eslint_d'>;
}
declare module 'eslint_d/bin/eslint.js' {
  declare module.exports: $Exports<'eslint_d/bin/eslint'>;
}
declare module 'eslint_d/lib/linter.js' {
  declare module.exports: $Exports<'eslint_d/lib/linter'>;
}
declare module 'eslint_d/lib/options.js' {
  declare module.exports: $Exports<'eslint_d/lib/options'>;
}
