// flow-typed signature: 92c1af7094ef970c469402373175e5ae
// flow-typed version: <<STUB>>/fpx_v0.7.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fpx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fpx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fpx/dist/fpx' {
  declare module.exports: any;
}

declare module 'fpx/es/fpx' {
  declare module.exports: any;
}

declare module 'fpx/src/fpx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fpx/dist/fpx.js' {
  declare module.exports: $Exports<'fpx/dist/fpx'>;
}
declare module 'fpx/es/fpx.js' {
  declare module.exports: $Exports<'fpx/es/fpx'>;
}
declare module 'fpx/src/fpx.js' {
  declare module.exports: $Exports<'fpx/src/fpx'>;
}
