// flow-typed signature: 50f78007837cbbeaed389eb499b5c6bb
// flow-typed version: <<STUB>>/googleapis_v27.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'googleapis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'googleapis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'googleapis/build/src/apis/abusiveexperiencereport/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer2/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v2.0' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexperiencereport/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/datatransfer_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/directory_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/reports_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsense/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsensehost/v4.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analytics/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analytics/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analyticsreporting/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androiddeviceprovisioning/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidenterprise/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidmanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta5' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appsactivity/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appstate/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquery/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquerydatatransfer/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/blogger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/blogger/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/books/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/calendar/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/chat/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/civicinfo/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/classroom/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbilling/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbuild/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouddebugger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouderrorreporting/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudfunctions/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudfunctions/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudiot/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudkms/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudshell/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudshell/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtasks/v2beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtrace/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtrace/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouduseraccounts/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouduseraccounts/beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouduseraccounts/vm_alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouduseraccounts/vm_beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/container/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/container/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/content/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/content/v2sandbox' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/customsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataflow/v1b3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataproc/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataproc/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/v2beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/v2.8' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/v3.0' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dialogflow/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/digitalassetlinks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/discovery/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dlp/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dlp/v2beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclickbidmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclicksearch/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/drive/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/drive/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebasedynamiclinks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebaserules/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firestore/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fitness/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fusiontables/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fusiontables/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/games/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesConfiguration/v1configuration' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesManagement/v1management' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v1alpha2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v2alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gmail/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupsmigration/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupssettings/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/iam/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/identitytoolkit/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/kgsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/licensing/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/logging/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/logging/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/manufacturers/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/mirror/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/ml/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/monitoring/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oauth2/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oauth2/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/partners/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/people/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/playcustomapp/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plus/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plusDomains/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/poly/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/prediction/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/prediction/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/prediction/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/prediction/v1.5' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/prediction/v1.6' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/proximitybeacon/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1beta1a' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapool/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapool/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapoolupdater/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/reseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/resourceviews/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/resourceviews/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/runtimeconfig/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/runtimeconfig/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/safebrowsing/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/script/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/searchconsole/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceconsumermanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicecontrol/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicemanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceusage/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceuser/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sheets/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/siteVerification/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/slides/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sourcerepo/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spanner/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spectrum/v1explorer' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/speech/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/speech/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sqladmin/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sqladmin/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storagetransfer/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/streetviewpublish/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/surveys/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tagmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tagmanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/taskqueue/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/taskqueue/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tasks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/testing/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/toolresults/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tpu/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/translate/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/urlshortener/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vault/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/videointelligence/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1p1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1p2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webfonts/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webmasters/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtube/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubereporting/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/api' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/apirequest' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/discovery' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/endpoint' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/googleapis' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/lib/schema' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/scripts/generate' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/scripts/generator_utils' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/scripts/generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'googleapis/build/src/apis/abusiveexperiencereport/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/abusiveexperiencereport/v1'>;
}
declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/acceleratedmobilepageurl/v1'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.2'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.3'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.4'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer2/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer2/v2beta1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v1.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v1.1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v2.0.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v2.0'>;
}
declare module 'googleapis/build/src/apis/adexperiencereport/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexperiencereport/v1'>;
}
declare module 'googleapis/build/src/apis/admin/datatransfer_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/datatransfer_v1'>;
}
declare module 'googleapis/build/src/apis/admin/directory_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/directory_v1'>;
}
declare module 'googleapis/build/src/apis/admin/reports_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/reports_v1'>;
}
declare module 'googleapis/build/src/apis/adsense/v1.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsense/v1.4'>;
}
declare module 'googleapis/build/src/apis/adsensehost/v4.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsensehost/v4.1'>;
}
declare module 'googleapis/build/src/apis/analytics/v2.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analytics/v2.4'>;
}
declare module 'googleapis/build/src/apis/analytics/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analytics/v3'>;
}
declare module 'googleapis/build/src/apis/analyticsreporting/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analyticsreporting/v4'>;
}
declare module 'googleapis/build/src/apis/androiddeviceprovisioning/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androiddeviceprovisioning/v1'>;
}
declare module 'googleapis/build/src/apis/androidenterprise/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidenterprise/v1'>;
}
declare module 'googleapis/build/src/apis/androidmanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidmanagement/v1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v1.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v1.1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v2'>;
}
declare module 'googleapis/build/src/apis/appengine/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1'>;
}
declare module 'googleapis/build/src/apis/appengine/v1alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1alpha'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta4'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta5.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta5'>;
}
declare module 'googleapis/build/src/apis/appsactivity/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appsactivity/v1'>;
}
declare module 'googleapis/build/src/apis/appstate/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appstate/v1'>;
}
declare module 'googleapis/build/src/apis/bigquery/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquery/v2'>;
}
declare module 'googleapis/build/src/apis/bigquerydatatransfer/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquerydatatransfer/v1'>;
}
declare module 'googleapis/build/src/apis/blogger/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/blogger/v2'>;
}
declare module 'googleapis/build/src/apis/blogger/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/blogger/v3'>;
}
declare module 'googleapis/build/src/apis/books/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/books/v1'>;
}
declare module 'googleapis/build/src/apis/calendar/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/calendar/v3'>;
}
declare module 'googleapis/build/src/apis/chat/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/chat/v1'>;
}
declare module 'googleapis/build/src/apis/civicinfo/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/civicinfo/v2'>;
}
declare module 'googleapis/build/src/apis/classroom/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/classroom/v1'>;
}
declare module 'googleapis/build/src/apis/cloudbilling/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbilling/v1'>;
}
declare module 'googleapis/build/src/apis/cloudbuild/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbuild/v1'>;
}
declare module 'googleapis/build/src/apis/clouddebugger/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouddebugger/v2'>;
}
declare module 'googleapis/build/src/apis/clouderrorreporting/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouderrorreporting/v1beta1'>;
}
declare module 'googleapis/build/src/apis/cloudfunctions/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudfunctions/v1'>;
}
declare module 'googleapis/build/src/apis/cloudfunctions/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudfunctions/v1beta2'>;
}
declare module 'googleapis/build/src/apis/cloudiot/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudiot/v1'>;
}
declare module 'googleapis/build/src/apis/cloudkms/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudkms/v1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v1beta1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v2beta1'>;
}
declare module 'googleapis/build/src/apis/cloudshell/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudshell/v1'>;
}
declare module 'googleapis/build/src/apis/cloudshell/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudshell/v1alpha1'>;
}
declare module 'googleapis/build/src/apis/cloudtasks/v2beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtasks/v2beta2'>;
}
declare module 'googleapis/build/src/apis/cloudtrace/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtrace/v1'>;
}
declare module 'googleapis/build/src/apis/cloudtrace/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtrace/v2'>;
}
declare module 'googleapis/build/src/apis/clouduseraccounts/alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouduseraccounts/alpha'>;
}
declare module 'googleapis/build/src/apis/clouduseraccounts/beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouduseraccounts/beta'>;
}
declare module 'googleapis/build/src/apis/clouduseraccounts/vm_alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouduseraccounts/vm_alpha'>;
}
declare module 'googleapis/build/src/apis/clouduseraccounts/vm_beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouduseraccounts/vm_beta'>;
}
declare module 'googleapis/build/src/apis/compute/alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/alpha'>;
}
declare module 'googleapis/build/src/apis/compute/beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/beta'>;
}
declare module 'googleapis/build/src/apis/compute/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/v1'>;
}
declare module 'googleapis/build/src/apis/container/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/container/v1'>;
}
declare module 'googleapis/build/src/apis/container/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/container/v1beta1'>;
}
declare module 'googleapis/build/src/apis/content/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/content/v2'>;
}
declare module 'googleapis/build/src/apis/content/v2sandbox.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/content/v2sandbox'>;
}
declare module 'googleapis/build/src/apis/customsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/customsearch/v1'>;
}
declare module 'googleapis/build/src/apis/dataflow/v1b3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataflow/v1b3'>;
}
declare module 'googleapis/build/src/apis/dataproc/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataproc/v1'>;
}
declare module 'googleapis/build/src/apis/dataproc/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataproc/v1beta2'>;
}
declare module 'googleapis/build/src/apis/datastore/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1'>;
}
declare module 'googleapis/build/src/apis/datastore/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1beta1'>;
}
declare module 'googleapis/build/src/apis/datastore/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1beta3'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/alpha'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/v2'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/v2beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/v2beta'>;
}
declare module 'googleapis/build/src/apis/dfareporting/v2.8.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/v2.8'>;
}
declare module 'googleapis/build/src/apis/dfareporting/v3.0.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/v3.0'>;
}
declare module 'googleapis/build/src/apis/dialogflow/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dialogflow/v2beta1'>;
}
declare module 'googleapis/build/src/apis/digitalassetlinks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/digitalassetlinks/v1'>;
}
declare module 'googleapis/build/src/apis/discovery/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/discovery/v1'>;
}
declare module 'googleapis/build/src/apis/dlp/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dlp/v2beta1'>;
}
declare module 'googleapis/build/src/apis/dlp/v2beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dlp/v2beta2'>;
}
declare module 'googleapis/build/src/apis/dns/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v1'>;
}
declare module 'googleapis/build/src/apis/dns/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v1beta2'>;
}
declare module 'googleapis/build/src/apis/dns/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v2beta1'>;
}
declare module 'googleapis/build/src/apis/doubleclickbidmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclickbidmanager/v1'>;
}
declare module 'googleapis/build/src/apis/doubleclicksearch/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclicksearch/v2'>;
}
declare module 'googleapis/build/src/apis/drive/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/drive/v2'>;
}
declare module 'googleapis/build/src/apis/drive/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/drive/v3'>;
}
declare module 'googleapis/build/src/apis/firebasedynamiclinks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebasedynamiclinks/v1'>;
}
declare module 'googleapis/build/src/apis/firebaserules/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebaserules/v1'>;
}
declare module 'googleapis/build/src/apis/firestore/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firestore/v1beta1'>;
}
declare module 'googleapis/build/src/apis/fitness/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fitness/v1'>;
}
declare module 'googleapis/build/src/apis/fusiontables/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fusiontables/v1'>;
}
declare module 'googleapis/build/src/apis/fusiontables/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fusiontables/v2'>;
}
declare module 'googleapis/build/src/apis/games/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/games/v1'>;
}
declare module 'googleapis/build/src/apis/gamesConfiguration/v1configuration.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesConfiguration/v1configuration'>;
}
declare module 'googleapis/build/src/apis/gamesManagement/v1management.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesManagement/v1management'>;
}
declare module 'googleapis/build/src/apis/genomics/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v1'>;
}
declare module 'googleapis/build/src/apis/genomics/v1alpha2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v1alpha2'>;
}
declare module 'googleapis/build/src/apis/genomics/v2alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v2alpha1'>;
}
declare module 'googleapis/build/src/apis/gmail/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gmail/v1'>;
}
declare module 'googleapis/build/src/apis/groupsmigration/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupsmigration/v1'>;
}
declare module 'googleapis/build/src/apis/groupssettings/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupssettings/v1'>;
}
declare module 'googleapis/build/src/apis/iam/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/iam/v1'>;
}
declare module 'googleapis/build/src/apis/identitytoolkit/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/identitytoolkit/v3'>;
}
declare module 'googleapis/build/src/apis/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/index'>;
}
declare module 'googleapis/build/src/apis/kgsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/kgsearch/v1'>;
}
declare module 'googleapis/build/src/apis/language/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1'>;
}
declare module 'googleapis/build/src/apis/language/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1beta1'>;
}
declare module 'googleapis/build/src/apis/language/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1beta2'>;
}
declare module 'googleapis/build/src/apis/licensing/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/licensing/v1'>;
}
declare module 'googleapis/build/src/apis/logging/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/logging/v2'>;
}
declare module 'googleapis/build/src/apis/logging/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/logging/v2beta1'>;
}
declare module 'googleapis/build/src/apis/manufacturers/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/manufacturers/v1'>;
}
declare module 'googleapis/build/src/apis/mirror/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/mirror/v1'>;
}
declare module 'googleapis/build/src/apis/ml/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/ml/v1'>;
}
declare module 'googleapis/build/src/apis/monitoring/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/monitoring/v3'>;
}
declare module 'googleapis/build/src/apis/oauth2/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oauth2/v1'>;
}
declare module 'googleapis/build/src/apis/oauth2/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oauth2/v2'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1alpha'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1beta'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/v1'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/v2'>;
}
declare module 'googleapis/build/src/apis/partners/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/partners/v2'>;
}
declare module 'googleapis/build/src/apis/people/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/people/v1'>;
}
declare module 'googleapis/build/src/apis/playcustomapp/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/playcustomapp/v1'>;
}
declare module 'googleapis/build/src/apis/plus/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plus/v1'>;
}
declare module 'googleapis/build/src/apis/plusDomains/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plusDomains/v1'>;
}
declare module 'googleapis/build/src/apis/poly/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/poly/v1'>;
}
declare module 'googleapis/build/src/apis/prediction/v1.2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/prediction/v1.2'>;
}
declare module 'googleapis/build/src/apis/prediction/v1.3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/prediction/v1.3'>;
}
declare module 'googleapis/build/src/apis/prediction/v1.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/prediction/v1.4'>;
}
declare module 'googleapis/build/src/apis/prediction/v1.5.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/prediction/v1.5'>;
}
declare module 'googleapis/build/src/apis/prediction/v1.6.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/prediction/v1.6'>;
}
declare module 'googleapis/build/src/apis/proximitybeacon/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/proximitybeacon/v1beta1'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1beta1a.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1beta1a'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1beta2'>;
}
declare module 'googleapis/build/src/apis/replicapool/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapool/v1beta1'>;
}
declare module 'googleapis/build/src/apis/replicapool/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapool/v1beta2'>;
}
declare module 'googleapis/build/src/apis/replicapoolupdater/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapoolupdater/v1beta1'>;
}
declare module 'googleapis/build/src/apis/reseller/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/reseller/v1'>;
}
declare module 'googleapis/build/src/apis/resourceviews/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/resourceviews/v1beta1'>;
}
declare module 'googleapis/build/src/apis/resourceviews/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/resourceviews/v1beta2'>;
}
declare module 'googleapis/build/src/apis/runtimeconfig/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/runtimeconfig/v1'>;
}
declare module 'googleapis/build/src/apis/runtimeconfig/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/runtimeconfig/v1beta1'>;
}
declare module 'googleapis/build/src/apis/safebrowsing/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/safebrowsing/v4'>;
}
declare module 'googleapis/build/src/apis/script/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/script/v1'>;
}
declare module 'googleapis/build/src/apis/searchconsole/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/searchconsole/v1'>;
}
declare module 'googleapis/build/src/apis/serviceconsumermanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceconsumermanagement/v1'>;
}
declare module 'googleapis/build/src/apis/servicecontrol/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicecontrol/v1'>;
}
declare module 'googleapis/build/src/apis/servicemanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicemanagement/v1'>;
}
declare module 'googleapis/build/src/apis/serviceusage/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceusage/v1'>;
}
declare module 'googleapis/build/src/apis/serviceuser/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceuser/v1'>;
}
declare module 'googleapis/build/src/apis/sheets/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sheets/v4'>;
}
declare module 'googleapis/build/src/apis/siteVerification/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/siteVerification/v1'>;
}
declare module 'googleapis/build/src/apis/slides/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/slides/v1'>;
}
declare module 'googleapis/build/src/apis/sourcerepo/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sourcerepo/v1'>;
}
declare module 'googleapis/build/src/apis/spanner/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spanner/v1'>;
}
declare module 'googleapis/build/src/apis/spectrum/v1explorer.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spectrum/v1explorer'>;
}
declare module 'googleapis/build/src/apis/speech/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/speech/v1'>;
}
declare module 'googleapis/build/src/apis/speech/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/speech/v1beta1'>;
}
declare module 'googleapis/build/src/apis/sqladmin/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sqladmin/v1beta3'>;
}
declare module 'googleapis/build/src/apis/sqladmin/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sqladmin/v1beta4'>;
}
declare module 'googleapis/build/src/apis/storage/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1'>;
}
declare module 'googleapis/build/src/apis/storage/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1beta1'>;
}
declare module 'googleapis/build/src/apis/storage/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1beta2'>;
}
declare module 'googleapis/build/src/apis/storagetransfer/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storagetransfer/v1'>;
}
declare module 'googleapis/build/src/apis/streetviewpublish/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/streetviewpublish/v1'>;
}
declare module 'googleapis/build/src/apis/surveys/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/surveys/v2'>;
}
declare module 'googleapis/build/src/apis/tagmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tagmanager/v1'>;
}
declare module 'googleapis/build/src/apis/tagmanager/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tagmanager/v2'>;
}
declare module 'googleapis/build/src/apis/taskqueue/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/taskqueue/v1beta1'>;
}
declare module 'googleapis/build/src/apis/taskqueue/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/taskqueue/v1beta2'>;
}
declare module 'googleapis/build/src/apis/tasks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tasks/v1'>;
}
declare module 'googleapis/build/src/apis/testing/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/testing/v1'>;
}
declare module 'googleapis/build/src/apis/toolresults/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/toolresults/v1beta3'>;
}
declare module 'googleapis/build/src/apis/tpu/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tpu/v1alpha1'>;
}
declare module 'googleapis/build/src/apis/translate/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/translate/v2'>;
}
declare module 'googleapis/build/src/apis/urlshortener/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/urlshortener/v1'>;
}
declare module 'googleapis/build/src/apis/vault/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vault/v1'>;
}
declare module 'googleapis/build/src/apis/videointelligence/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/videointelligence/v1beta1'>;
}
declare module 'googleapis/build/src/apis/vision/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1'>;
}
declare module 'googleapis/build/src/apis/vision/v1p1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1p1beta1'>;
}
declare module 'googleapis/build/src/apis/vision/v1p2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1p2beta1'>;
}
declare module 'googleapis/build/src/apis/webfonts/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webfonts/v1'>;
}
declare module 'googleapis/build/src/apis/webmasters/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webmasters/v3'>;
}
declare module 'googleapis/build/src/apis/youtube/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtube/v3'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/v1'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/v1beta1'>;
}
declare module 'googleapis/build/src/apis/youtubereporting/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubereporting/v1'>;
}
declare module 'googleapis/build/src/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/index'>;
}
declare module 'googleapis/build/src/lib/api.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/api'>;
}
declare module 'googleapis/build/src/lib/apirequest.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/apirequest'>;
}
declare module 'googleapis/build/src/lib/discovery.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/discovery'>;
}
declare module 'googleapis/build/src/lib/endpoint.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/endpoint'>;
}
declare module 'googleapis/build/src/lib/googleapis.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/googleapis'>;
}
declare module 'googleapis/build/src/lib/schema.js' {
  declare module.exports: $Exports<'googleapis/build/src/lib/schema'>;
}
declare module 'googleapis/build/src/scripts/generate.js' {
  declare module.exports: $Exports<'googleapis/build/src/scripts/generate'>;
}
declare module 'googleapis/build/src/scripts/generator_utils.js' {
  declare module.exports: $Exports<'googleapis/build/src/scripts/generator_utils'>;
}
declare module 'googleapis/build/src/scripts/generator.js' {
  declare module.exports: $Exports<'googleapis/build/src/scripts/generator'>;
}
