// flow-typed signature: f7cf51f105db953a15311d0518b40c87
// flow-typed version: <<STUB>>/xhttp_v0.11.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xhttp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xhttp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xhttp/dist/xhttp-browser' {
  declare module.exports: any;
}

declare module 'xhttp/es/xhttp-browser' {
  declare module.exports: any;
}

declare module 'xhttp/lib/xhttp-node' {
  declare module.exports: any;
}

declare module 'xhttp/node' {
  declare module.exports: any;
}

declare module 'xhttp/src/xhttp-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xhttp/dist/xhttp-browser.js' {
  declare module.exports: $Exports<'xhttp/dist/xhttp-browser'>;
}
declare module 'xhttp/es/xhttp-browser.js' {
  declare module.exports: $Exports<'xhttp/es/xhttp-browser'>;
}
declare module 'xhttp/lib/xhttp-node.js' {
  declare module.exports: $Exports<'xhttp/lib/xhttp-node'>;
}
declare module 'xhttp/node.js' {
  declare module.exports: $Exports<'xhttp/node'>;
}
declare module 'xhttp/src/xhttp-browser.js' {
  declare module.exports: $Exports<'xhttp/src/xhttp-browser'>;
}
